const fs = require('fs');
let c = fs.readFileSync('app/membresias/page.tsx', 'utf8');

c = c.replace(/\u01ed/g, 'á');
c = c.replace(/\u01f8/g, 'é');
c = c.replace(/\u01e7/g, 'ú');
c = c.replace(/\u011b/g, 'ě');

c = c.replace(/Membresas/g, 'Membresías');
c = c.replace(/Membresa/g, 'Membresía');
c = c.replace(/Inasistencia/g, 'Inasistencia');
c = c.replace(/das/g, 'días');
c = c.replace(/Hola/g, '¡Hola');
c = c.replace(/Todo/g, '¿Todo');
c = c.replace(/Felicitacin/g, 'Felicitación');
c = c.replace(/Felicidades/g, '¡Felicidades');
c = c.replace(/as/g, 'así');
c = c.replace(/Renueva/g, '¡Renueva');
c = c.replace(/contraseas/g, 'contraseñas');
c = c.replace(/Contrasea/g, 'Contraseña');
c = c.replace(/contrasea/g, 'contraseña');
c = c.replace(/nmero/g, 'número');
c = c.replace(/Renovacin/g, 'Renovación');
c = c.replace(/exitosos/g, 'exitosos');
c = c.replace(/Duracin/g, 'Duración');
c = c.replace(/Aadir/g, 'Añadir');
c = c.replace(/Mtodo/g, 'Método');
c = c.replace(/N de Transaccin/g, 'Nº de Transacción');
c = c.replace(/N de Referencia/g, 'Nº de Referencia');
c = c.replace(/Cmara/g, 'Cámara');
c = c.replace(/Cdula/g, 'Cédula');
c = c.replace(/Telfono/g, 'Teléfono');
c = c.replace(/Direccin/g, 'Dirección');
c = c.replace(/Ttulo del botn/g, 'Título del botón');
c = c.replace(/promocin/g, 'promoción');
c = c.replace(/Promocin/g, 'Promoción');
c = c.replace(/comuncate/g, 'comunícate');
c = c.replace(/sltimo/g, 'Último');
c = c.replace(/FULLSCREEN/g, 'FULLSCREEN');
c = c.replace(/Mvil/g, 'Móvil');
c = c.replace(/Crdito/g, 'Crédito');

fs.writeFileSync('app/membresias/page.tsx', c, 'utf8');
console.log("Safe replace done");
